version: "3.8"
services:
  jellyfin:
    image: docker.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    volumes:
      - /home/nshiu/arrDATA/config/Jellyfin:/config
      - /home/nshiu/arrDATA/media:/media
      # - /dev/shm:/transcode
    tmpfs:
      - /transcode:size=4G,mode=1777
    ports:
      - 8096:8096
    environment:
      - TZ=Asia/Taipei
      - PUID=1000
      - PGID=1000
      - JELLYFIN_ADDITIONAL_GID=109
      - JELLYFIN_PublishedServerUrl=http://10.0.1.51
    restart: unless-stopped
