services:
  plex-server:

    # cap_drop:
    #   - "AUDIT_CONTROL"
    #   - "BLOCK_SUSPEND"
    #   - "DAC_READ_SEARCH"
    #   - "IPC_LOCK"
    #   - "IPC_OWNER"
    #   - "LEASE"
    #   - "LINUX_IMMUTABLE"
    #   - "MAC_ADMIN"
    #   - "MAC_OVERRIDE"
    #   - "NET_ADMIN"
    #   - "NET_BROADCAST"
    #   - "SYSLOG"
    #   - "SYS_ADMIN"
    #   - "SYS_BOOT"
    #   - "SYS_MODULE"
    #   - "SYS_NICE"
    #   - "SYS_PACCT"
    #   - "SYS_PTRACE"
    #   - "SYS_RAWIO"
    #   - "SYS_RESOURCE"
    #   - "SYS_TIME"
    #   - "SYS_TTY_CONFIG"
    #   - "WAKE_ALARM"

    container_name: "plex-server"

    # entrypoint:
    #   - "/init"

    environment:
      - "TZ=Asia/Taipei"
      - "VERSION=docker"
      - "PLEX_CLAIM=claim-rvPWo4S9154f_fDcxBHk"
      # - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      # - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      # - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      # - "S6_VERBOSITY=1"
      # - "S6_STAGE2_HOOK=/docker-mods"
      # - "VIRTUAL_ENV=/lsiopy"
      # - "LSIO_FIRST_PARTY=true"
      # - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility,graphics"
      # - "DEBIAN_FRONTEND=noninteractive"
      # - "PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new"
      # - "PLEX_ARCH=amd64"
      # - "PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support"
      # - "PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver"
      # - "PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6"
      # - "PLEX_MEDIA_SERVER_USER=abc"
      # - "PLEX_MEDIA_SERVER_INFO_VENDOR=Docker"
      # - "PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)"
      # - "TMPDIR=/run/plex-temp"
      # - "ATTACHED_DEVICES_PERMS=/dev/dri /dev/dvb -type c"
      - "PUID=1000"
      - "PGID=1000"

    # expose:
    #   - "1900/udp"
    #   - "32400/tcp"
    #   - "32410/udp"
    #   - "32412/udp"
    #   - "32413/udp"
    #   - "32414/udp"
    #   - "32469/tcp"
    #   - "5353/udp"
    #   - "8324/tcp"

    hostname: "plexserver"

    image: "docker.io/linuxserver/plex:latest"

    # ipc: "private"

    # labels:
    #   build_version: "Linuxserver.io version:- 1.42.2.10156-f737b826c-ls291 Build-date:- 2026-01-28T20:54:44+00:00"
    #   maintainer: "thelamer"
    #   org.opencontainers.image.authors: "linuxserver.io"
    #   org.opencontainers.image.created: "2026-01-28T20:54:44+00:00"
    #   org.opencontainers.image.description: "[Plex](https://plex.tv) organizes video, music and photos\
    #     \ from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices.\
    #     \ This container is packaged as a standalone Plex Media Server. Straightforward design and bulk\
    #     \ actions mean getting things done faster."
    #   org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-plex"
    #   org.opencontainers.image.licenses: "GPL-3.0-only"
    #   org.opencontainers.image.ref.name: "2d9cdff1636eca28014ccc437b1ff200df4c18c4"
    #   org.opencontainers.image.revision: "2d9cdff1636eca28014ccc437b1ff200df4c18c4"
    #   org.opencontainers.image.source: "https://github.com/linuxserver/docker-plex"
    #   org.opencontainers.image.title: "Plex"
    #   org.opencontainers.image.url: "https://github.com/linuxserver/docker-plex/packages"
    #   org.opencontainers.image.vendor: "linuxserver.io"
    #   org.opencontainers.image.version: "1.42.2.10156-f737b826c-ls291"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    restart: "unless-stopped"

    volumes:
      - "/home/nshiu/arrDATA/config/PlexServer:/config"
      - "/home/nshiu/arrDATA/media:/media"

    # working_dir: "/"

version: "3.6"
